name: On Push

on: [ pull_request ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore tools
        run: dotnet tool restore
      - name: Restore dependencies
        run: dotnet restore
      # - name: Run F# linter
      #   run: dotnet fsharplint lint AspFeat.sln
      - name: Run tests
        run: dotnet test --no-restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
